// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -destination=service_mock.go -source=handler.go -package=handlers
//

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	reflect "reflect"

	models "github.com/Sugyk/avito_test_task/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateOrUpdateTeam mocks base method.
func (m *MockService) CreateOrUpdateTeam(ctx context.Context, team *models.Team) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateTeam", ctx, team)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateTeam indicates an expected call of CreateOrUpdateTeam.
func (mr *MockServiceMockRecorder) CreateOrUpdateTeam(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateTeam", reflect.TypeOf((*MockService)(nil).CreateOrUpdateTeam), ctx, team)
}

// GetTeamWithMembers mocks base method.
func (m *MockService) GetTeamWithMembers(ctx context.Context, teamName string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamWithMembers", ctx, teamName)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamWithMembers indicates an expected call of GetTeamWithMembers.
func (mr *MockServiceMockRecorder) GetTeamWithMembers(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamWithMembers", reflect.TypeOf((*MockService)(nil).GetTeamWithMembers), ctx, teamName)
}

// PullRequestCreate mocks base method.
func (m *MockService) PullRequestCreate(ctx context.Context, pr *models.PullRequest) (models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestCreate", ctx, pr)
	ret0, _ := ret[0].(models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequestCreate indicates an expected call of PullRequestCreate.
func (mr *MockServiceMockRecorder) PullRequestCreate(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestCreate", reflect.TypeOf((*MockService)(nil).PullRequestCreate), ctx, pr)
}

// PullRequestMerge mocks base method.
func (m *MockService) PullRequestMerge(ctx context.Context, pr *models.PullRequest) (models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestMerge", ctx, pr)
	ret0, _ := ret[0].(models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequestMerge indicates an expected call of PullRequestMerge.
func (mr *MockServiceMockRecorder) PullRequestMerge(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestMerge", reflect.TypeOf((*MockService)(nil).PullRequestMerge), ctx, pr)
}

// PullRequestReassign mocks base method.
func (m *MockService) PullRequestReassign(ctx context.Context, prID, oldUserID string) (models.PullRequest, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestReassign", ctx, prID, oldUserID)
	ret0, _ := ret[0].(models.PullRequest)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PullRequestReassign indicates an expected call of PullRequestReassign.
func (mr *MockServiceMockRecorder) PullRequestReassign(ctx, prID, oldUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestReassign", reflect.TypeOf((*MockService)(nil).PullRequestReassign), ctx, prID, oldUserID)
}

// UsersGetReview mocks base method.
func (m *MockService) UsersGetReview(ctx context.Context, userID string) ([]models.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsersGetReview", ctx, userID)
	ret0, _ := ret[0].([]models.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsersGetReview indicates an expected call of UsersGetReview.
func (mr *MockServiceMockRecorder) UsersGetReview(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersGetReview", reflect.TypeOf((*MockService)(nil).UsersGetReview), ctx, userID)
}

// UsersSetIsActive mocks base method.
func (m *MockService) UsersSetIsActive(ctx context.Context, userID string, isActive bool) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsersSetIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsersSetIsActive indicates an expected call of UsersSetIsActive.
func (mr *MockServiceMockRecorder) UsersSetIsActive(ctx, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersSetIsActive", reflect.TypeOf((*MockService)(nil).UsersSetIsActive), ctx, userID, isActive)
}
