// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -destination=service_mock.go -source=handler.go -package=handlers
//

// Package handlers is a generated GoMock package.
package handlers

import (
	reflect "reflect"

	models "github.com/Sugyk/avito_test_task/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateOrUpdateTeam mocks base method.
func (m *MockService) CreateOrUpdateTeam(team *models.Team) (models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateTeam", team)
	ret0, _ := ret[0].(models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateTeam indicates an expected call of CreateOrUpdateTeam.
func (mr *MockServiceMockRecorder) CreateOrUpdateTeam(team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateTeam", reflect.TypeOf((*MockService)(nil).CreateOrUpdateTeam), team)
}

// GetTeamWithMembers mocks base method.
func (m *MockService) GetTeamWithMembers(teamName string) (models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamWithMembers", teamName)
	ret0, _ := ret[0].(models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamWithMembers indicates an expected call of GetTeamWithMembers.
func (mr *MockServiceMockRecorder) GetTeamWithMembers(teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamWithMembers", reflect.TypeOf((*MockService)(nil).GetTeamWithMembers), teamName)
}

// PullRequestCreate mocks base method.
func (m *MockService) PullRequestCreate(pr *models.PullRequest) (models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestCreate", pr)
	ret0, _ := ret[0].(models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequestCreate indicates an expected call of PullRequestCreate.
func (mr *MockServiceMockRecorder) PullRequestCreate(pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestCreate", reflect.TypeOf((*MockService)(nil).PullRequestCreate), pr)
}

// PullRequestMerge mocks base method.
func (m *MockService) PullRequestMerge(pr *models.PullRequest) (models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestMerge", pr)
	ret0, _ := ret[0].(models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequestMerge indicates an expected call of PullRequestMerge.
func (mr *MockServiceMockRecorder) PullRequestMerge(pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestMerge", reflect.TypeOf((*MockService)(nil).PullRequestMerge), pr)
}

// UsersSetIsActive mocks base method.
func (m *MockService) UsersSetIsActive(userID string, isActive bool) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsersSetIsActive", userID, isActive)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsersSetIsActive indicates an expected call of UsersSetIsActive.
func (mr *MockServiceMockRecorder) UsersSetIsActive(userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersSetIsActive", reflect.TypeOf((*MockService)(nil).UsersSetIsActive), userID, isActive)
}
